on:
  push:
    branches:
      - main
name: Deploy
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: sv14703.xserver.jp
          FTP_USERNAME: todotest
          FTP_PASSWORD: rn1l2ilk
          LOCAL_DIR: ./
          REMOTE_DIR: /todotest.xsrv.jp/public_html/
